spring.application.name=quoteEngine
spring.h2.console.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=quote-engine
spring.kafka.consumer.auto-offset-reset=earliest